name: hello

on:
  push:
  pull_request:

jobs:
  j1:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ vars.a }}
      - run: echo ${{ secrets.b }}
  j2:
    environment: main
    runs-on: ubuntu-latest
    needs: j1
    steps:
      - run: echo ${{ vars.a }}
      - run: echo ${{ secrets.b }}
